development: &default
  adapter: postgresql
  database: mocket_development
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  port: <%= ENV["DB_PORT"] %>
  host: localhost
test:
  <<: *default
  database: mocket_test

production:
  <<: *default
  database: mocket_production